apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-credentials
  labels:
    {{- include "operator.labels" . | nindent 4 }}
stringData:
  htpasswd: {{ .Values.htpasswd | quote }}
