---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-clusterrole
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - airflow.stackable.tech
      - superset.stackable.tech
      - hive.stackable.tech
      - opa.stackable.tech
      - secrets.stackable.tech
      - superset.stackable.tech
      - trino.stackable.tech
      - authentication.stackable.tech
      - s3.stackable.tech
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - watch
