---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
