---
self-hosted-runner:
  labels:
    # BuildJet machines we are using
    - buildjet-2vcpu-ubuntu-2204-arm
    - buildjet-4vcpu-ubuntu-2204-arm
    # Hosted runners currently unknown to actionlint
    - ubuntu-24.04-arm
