[workspace]
members = [
  "rust/*",
  "web",
  "."
]

[workspace.package]
version = "0.0.0-dev"

[workspace.dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.42.2" }
kube = { version = "0.82.2", default-features = false, features = ["client", "openssl-tls"] }
k8s-openapi = { version = "0.18.0", default-features = false, features = ["v1_26"] }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.16", features = ["native-tls"] }
serde = { version = "1.0.160", features = ["derive"] }
indexmap = { version = "1.9.3", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive"] }
tracing-subscriber = "0.3.17"
utoipa-swagger-ui = "3.1.3"
tracing-indicatif = "0.3.4"
clap_complete = "4.2.0"
phf_codegen = "0.11.1"
async-trait = "0.1.68"
lazy_static = "1.4.0"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
thiserror = "1.0.44"
indicatif = "0.17.5"
dotenvy = "0.15.7"
tracing = "0.1.37"
semver = "1.0.17"
bcrypt = "0.14.0"
utoipa = "3.3.0"
axum = "0.6.18"
snafu = "0.7.4"
which = "4.4.0"
tera = "1.18.1"
rand = "0.8.5"
phf = "0.11.1"
url = "2.3.1"
xdg = "2.4.1"
