[workspace]
members = ["rust/*", "web", "."]

[workspace.package]
version = "0.0.0-dev"
authors = ["Stackable GmbH <info@stackable.tech>"]
license = "OSL-3.0"
edition = "2021"
repository = "https://github.com/stackabletech/stackable-cockpit/"

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.6", features = ["http2", "headers"] }
bcrypt = "0.15"
clap = { version = "4.2.1", features = ["derive", "env"] }
clap_complete = "4.2"
comfy-table = { version = "7.0", features = ["custom_styling"] }
directories = "5.0"
dotenvy = "0.15"
futures = "0.3"
gobuild = "0.1.0-alpha.2"
indexmap = { version = "2.0", features = ["serde"] }
k8s-openapi = { version = "0.19", default-features = false, features = ["v1_27"] }
kube = { version = "0.85", default-features = false, features = ["client", "rustls-tls"] }
lazy_static = "1.4"
nu-ansi-term = "0.49"
once_cell = "1.18"
phf = "0.11"
phf_codegen = "0.11"
rand = "0.8"
regex = "1.9"
# We use the feature "rustls-tls-native-roots" instead of "rustls-tls" to avoid pulling in "webpki-roots" and hence MPL-2.0: https://github.com/rustls/webpki-roots/blob/main/LICENSE
reqwest = { version = "0.11.16", default-features = false, features = ["rustls-tls-native-roots"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
snafu = "0.7"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.47.0" }
tera = "1.18"
tokio = { version = "1.29.0", features = ["rt-multi-thread", "macros", "fs", "process"] }
tower-http = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.3"
utoipa = { version = "3.3", features = ["indexmap"] }
utoipa-swagger-ui = { version = "3.1", features = ["axum"] }
uuid = { version = "1.4.0", features = ["v4"] }
which = "4.4"

[patch."https://github.com/stackabletech/operator-rs.git"]
# TODO: Switch to released version
# We did not want to draw a release of operator-rs just for https://github.com/stackabletech/operator-rs/pull/634
# stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "main" }
