schema = 3

[mod]
  [mod."github.com/AdaLogics/go-fuzz-headers"]
    version = "v0.0.0-20230811130428-ced1acdcaa24"
    hash = "sha256-ezetyXdjgEK3A4QsOEfUJNBhd0kxb0s7UbX1ErZ1sAA="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20230124172434-306776ec8161"
    hash = "sha256-17hCoOE3HBv6cjpcukfBS6/ULgTuoUZ7RNbi5korH2M="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.3.2"
    hash = "sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg="
  [mod."github.com/MakeNowJust/heredoc"]
    version = "v1.0.0"
    hash = "sha256-8hKERAVV1Pew84kc9GkW23dcO8uIUx/+tJQLi+oPwqE="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.1"
    hash = "sha256-VKHIquwriyOL8A0qgtmap/3cGEOpDokOLtPg1w4xjMA="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.3"
    hash = "sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4="
  [mod."github.com/Masterminds/squirrel"]
    version = "v1.5.4"
    hash = "sha256-7UGz8TLcBI9HjU7zPqj9Gjp9Av+43mu0YCBV1mRy34o="
  [mod."github.com/Microsoft/hcsshim"]
    version = "v0.11.4"
    hash = "sha256-Lsagm4lFeerY/t55dvKJuFAghzg0JQFjUAfjyW1dSUQ="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20230301143203-a9d515a09cc2"
    hash = "sha256-UCENzt1c1tFgsAzK2TNq5s2g0tQMQ5PxFaQKe8hTL/A="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chai2010/gettext-go"]
    version = "v1.0.2"
    hash = "sha256-dwbhL7uAsAWGfX7Qmfa2hm0YClkbbB7ZHqOiPGP/L18="
  [mod."github.com/containerd/containerd"]
    version = "v1.7.12"
    hash = "sha256-VGamxCPJtzyybvdRKrAIlR838ODJchRn7P9C8OI0LV0="
  [mod."github.com/containerd/log"]
    version = "v0.1.0"
    hash = "sha256-vuE6Mie2gSxiN3jTKTZovjcbdBd1YEExb7IBe3GM+9s="
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.2.4"
    hash = "sha256-heCD0xMxlwnHCHcRBgTjVexHOLyWI2zRW3E8NFKoLzk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/distribution/reference"]
    version = "v0.5.0"
    hash = "sha256-nTlqurp/J/xOZeR0JcJMmE4GUHMMd5I+EOR7huzYuok="
  [mod."github.com/docker/cli"]
    version = "v24.0.7+incompatible"
    hash = "sha256-Vr0JShJCc/zu2dFbynNY1Bq/sbAxgekxo8WgdTXrx2A="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker"]
    version = "v24.0.9+incompatible"
    hash = "sha256-JZToreP7NNxIoPLTsA6NTIFlYCGHi1Kty4uzuA253Xw="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.8.0"
    hash = "sha256-fQ03ZgloW4DBIwic4ECRyzV3nA07cExSth1AMEgiP8E="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-metrics"]
    version = "v0.0.1"
    hash = "sha256-6pXkJyKTTrVbaE1D3IQ0gUUp9LTUd5yfprxClhAKzqw="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.11.1"
    hash = "sha256-Y5FxHo9hBDaIxaF12YYnhCta4lKQSPrQGFPNKUsEW28="
  [mod."github.com/evanphx/json-patch"]
    version = "v5.7.0+incompatible"
    hash = "sha256-6aTV41slcMtqRp2PdL4CKTDPUMoIXNP/tOgduzgGMCU="
  [mod."github.com/exponent-io/jsonpath"]
    version = "v0.0.0-20210407135951-1de76d718b3f"
    hash = "sha256-2wgJI2pvkaq2MoeUmLRaTBA8dIoEcwzKvw4qKJlhIec="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-errors/errors"]
    version = "v1.5.1"
    hash = "sha256-K/IEfka2mbBk6b0AbiMaxpvkY1pZgzhtT6knqoDovPk="
  [mod."github.com/go-gorp/gorp/v3"]
    version = "v3.1.0"
    hash = "sha256-z8AJoWp3fDJMNMYAi8kJdtzXDv8QyAd6bPYE58b2urs="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.1"
    hash = "sha256-WM4badoqxXlBmqCRrnmtNce63dLlr/FJav3BJSYHvaY="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.20.2"
    hash = "sha256-z9IZxP+JvJ1WvrHE7qbAZQqJ3XMx1uD0S611shTMna8="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.4"
    hash = "sha256-2/2MjQDQeQwbKHBos2+hSUdBYE4zvpdVbhU9j6QL7Is="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.7"
    hash = "sha256-fLS1tluqWOZWhDf5PeSFCYUGSBFe0kwYwmzca/DEugA="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/btree"]
    version = "v1.1.2"
    hash = "sha256-K7V2obq3pLM71Mg0vhhHtZ+gtaubwXPQx3xcIyZDCjM="
  [mod."github.com/google/gnostic-models"]
    version = "v0.6.8"
    hash = "sha256-YzA/XpvPyfdplJtHmAUdQk9P+j0NBwHhW9nj1DaGaoQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/google/uuid"]
    version = "v1.5.0"
    hash = "sha256-DasOte4xANR1VND5XEHKGhpGiyYq74TJmNrgWeIRX4U="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.1"
    hash = "sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.1"
    hash = "sha256-eHZ/U+eeE5tSgWc1jEDuBwtTRbXKP9fqP9zfW4Zw8T0="
  [mod."github.com/gosuri/uitable"]
    version = "v0.0.4"
    hash = "sha256-/SpsQ7j+3dEDC0UX9C+ZjQ8zY7taoqIOQspTqRb8oLk="
  [mod."github.com/gregjones/httpcache"]
    version = "v0.0.0-20190611155906-901d90724c79"
    hash = "sha256-AEfenLNBYwZjwHsMG48bpwUyUtjx1BBiK2W5HQruIBc="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/huandu/xstrings"]
    version = "v1.4.0"
    hash = "sha256-lw0qFsUNW6ZPXNwawpUSfJQjZ+/PKMLkC/yW64t1yng="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.16"
    hash = "sha256-gh2TEAq8YrZOEAf6SFW4AIcEEUguD68G+7/VUnBeWwM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.3.5"
    hash = "sha256-JEg/DpnDOPPUWtFiHQFUwt7+0TWsybPiG1WP6N5oVic="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.4"
    hash = "sha256-5E7dDtDKfL3jy7zJxHBMV57WlHZrP/OoEX5e6cOPba0="
  [mod."github.com/lann/builder"]
    version = "v0.0.0-20180802200727-47ae307949d0"
    hash = "sha256-NDZvsU6T2jVq5pfhp/VoJcMTq8DXKXiEkfZHloOX6c0="
  [mod."github.com/lann/ps"]
    version = "v0.0.0-20150810152359-62de8c46ede0"
    hash = "sha256-fHIjAtshTJWa67PzzgruqN1LdpQ7Zgc1qpEZWhjQTnU="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/liggitt/tabwriter"]
    version = "v0.0.0-20181228230101-89fcab3d43de"
    hash = "sha256-b6pLitORwgfGpOHpe45ykj00P17utbDv8bv6MCVoCBM="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/matttproud/golang_protobuf_extensions/v2"]
    version = "v2.0.0"
    hash = "sha256-gcAN8jKL0ve8pcgDkxr2Lc8CUBG39ri9QAp0zrzchEs="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/mittwald/go-helm-client"]
    version = "v0.12.9"
    hash = "sha256-dK6t69woohoWlUvl/nWmIcYf02JC7V0crKaqr9Vlkc8="
  [mod."github.com/moby/locker"]
    version = "v1.0.1"
    hash = "sha256-OcpbO3fLe0WtLDZFF1ntxoEBlEDjyoA8q8mVAQ0TLB8="
  [mod."github.com/moby/spdystream"]
    version = "v0.2.0"
    hash = "sha256-Feme5UoWuBCvnLPKw1ozKkF3SM7PAjjPFQZ3TJhghR0="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/monochromegane/go-gitignore"]
    version = "v0.0.0-20200626010858-205db1a8cc00"
    hash = "sha256-j1Mgb2TUUIiBcXB+slOkjtvcjmqSMEsG5RZYE7vGXOU="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/mxk/go-flowrate"]
    version = "v0.0.0-20140419014527-cca7078d478f"
    hash = "sha256-gRTfRfff/LRxC1SXXnQd2tV3UTcTx9qu90DJIVIaGn8="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0-rc5"
    hash = "sha256-wvg4aRpoZ3alRygfEehPg9p6N2Sv5umwx0WTxeIgyao="
  [mod."github.com/peterbourgon/diskv"]
    version = "v2.0.1+incompatible"
    hash = "sha256-K4mEVjH0eyxyYHQRxdbmgJT0AJrfucUwGB2BplRRt9c="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.18.0"
    hash = "sha256-kuC6WUg2j7A+9qnSp5VZSYo+oltgLvj/70TpqlCJIdE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.5.0"
    hash = "sha256-/sXlngf8AoEIeLIiaLg6Y7uYPVq7tI0qnLt0mUyKid4="
  [mod."github.com/prometheus/common"]
    version = "v0.45.0"
    hash = "sha256-N7CDcekAW8InquaVHHkuZ6gNCoW8J0yDlH5A+dj3cfE="
  [mod."github.com/prometheus/procfs"]
    version = "v0.12.0"
    hash = "sha256-Y4ZZmxIpVCO67zN3pGwSk2TcI88zvmGJkgwq9DRTwFw="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.4"
    hash = "sha256-B8tbL9K6ICLdm0lEhs9+h4cpjAfvFtNiFMGvQZmw0bM="
  [mod."github.com/rubenv/sql-migrate"]
    version = "v1.6.0"
    hash = "sha256-qSy0fP6/Qo6oE2Aw4FY+eojIKz4hoauoWeHFUlxQvUE="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.3.1"
    hash = "sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.0"
    hash = "sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/xeipuuv/gojsonschema"]
    version = "v1.2.0"
    hash = "sha256-1ERBEvxj3pvHkMS2mvmvmYRi8jgAaTquo5hwjDLAEdc="
  [mod."github.com/xlab/treeprint"]
    version = "v1.2.0"
    hash = "sha256-g85HyWGLZuD/TFXZzmXT+u9TA1xIT5escUVhnofsYQI="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.46.1"
    hash = "sha256-H7GeyxyGcxVRCnR0J7HvpWi3QhwsXGF/IunQMpfkXhw="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.21.0"
    hash = "sha256-MWC1fp41z3w3Y1wlECY12Q7sLeU4PRACZEesWTmDD9E="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.21.0"
    hash = "sha256-UH5fN59juP5GRiTpr5VUv4JGAE2o47LOyR7Ic6Yl/v4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.21.0"
    hash = "sha256-vjZsOaQCgTjz6WYim0YZHLnB/PC3CvTSpS97qkL2vz8="
  [mod."go.starlark.net"]
    version = "v0.0.0-20231121155337-90ade8b19d09"
    hash = "sha256-WZvhYul+2MGtUKcvZOtWVIeMdQOKTCapO3TfGbdLOVs="
  [mod."golang.org/x/crypto"]
    version = "v0.17.0"
    hash = "sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240103183307-be819d1f06fc"
    hash = "sha256-6hJzMfturiONTx7NLpsqarsnoIbx3kvk8QetcrnrbTQ="
  [mod."golang.org/x/net"]
    version = "v0.19.0"
    hash = "sha256-3M5rKEvJx4cO/q+06cGjR5sxF5JpnUWY0+fQttrWdT4="
  [mod."golang.org/x/oauth2"]
    version = "v0.15.0"
    hash = "sha256-exA/abu6WOR7Cwqa41LpnTD2xQNRZMYU5CnBKvXHx8Y="
  [mod."golang.org/x/sync"]
    version = "v0.5.0"
    hash = "sha256-EAKeODSsct5HhXPmpWJfulKSCkuUu6kkDttnjyZMNcI="
  [mod."golang.org/x/sys"]
    version = "v0.15.0"
    hash = "sha256-n7TlABF6179RzGq3gctPDKDPRtDfnwPdjNCMm8ps2KY="
  [mod."golang.org/x/term"]
    version = "v0.15.0"
    hash = "sha256-rsvtsE7sKmBwtR+mhJ8iUq93ZT8fV2LU+Pd69sh2es8="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."google.golang.org/appengine"]
    version = "v1.6.8"
    hash = "sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240102182953-50ed04b92917"
    hash = "sha256-OeWABQ7uSz7IlqTDSyxXKdlrzCC44aKxTkqMfXhzV8I="
  [mod."google.golang.org/grpc"]
    version = "v1.60.1"
    hash = "sha256-JJ3X6DTUZWYtM8i8izWTH9nDvCydzea31iZt6ULDvsw="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
  [mod."gopkg.in/evanphx/json-patch.v5"]
    version = "v5.7.0"
    hash = "sha256-6aTV41slcMtqRp2PdL4CKTDPUMoIXNP/tOgduzgGMCU="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."helm.sh/helm/v3"]
    version = "v3.14.4"
    hash = "sha256-GxJ7Vlcwn7DkFOfhLX44kQ0PYqGQHkYnbiV4p+GHL50="
  [mod."k8s.io/api"]
    version = "v0.29.0"
    hash = "sha256-43BzdI3ryD8Egui9FQuUyX4CQP6yNYv/8BxoDjrU96Q="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.29.0"
    hash = "sha256-wYkp3RSvrjQTm5RkdQB/FRHlvv2afd9fBGQL1pYaszY="
  [mod."k8s.io/apimachinery"]
    version = "v0.29.0"
    hash = "sha256-7Nrm7hh9yEJz/ikaaJTnMNrtpUYaOXuOL6wDTT08d1k="
  [mod."k8s.io/apiserver"]
    version = "v0.29.0"
    hash = "sha256-Zb4VGXo53+J+nb/UwUxe9EmYqNIKXpKsGNWrLeVhpFo="
  [mod."k8s.io/cli-runtime"]
    version = "v0.29.0"
    hash = "sha256-UDXeIGMHEZPUibNpsTE18xMRwy+jh2ve9Pmgn7i1nDU="
  [mod."k8s.io/client-go"]
    version = "v0.29.0"
    hash = "sha256-GuY06sFi5YaQ4h925hCgdzfIMUjTcKxupKP6h7RWI78="
  [mod."k8s.io/component-base"]
    version = "v0.29.0"
    hash = "sha256-tSpnzf/tg3Jog0YLMWmPWpTbb25zC6K8Nw+7zDe0b5c="
  [mod."k8s.io/klog/v2"]
    version = "v2.110.1"
    hash = "sha256-0nmkyVd1B4lnCLsPxtdJWDZW4EGOwcgYXnA6M9j01ss="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20240103195357-a9f8850cb432"
    hash = "sha256-84VvHLl6ANnTt0KPl7brcnEOhnvpFmdsjm541SBWmbM="
  [mod."k8s.io/kubectl"]
    version = "v0.29.0"
    hash = "sha256-uXk8gJw1/0nztBq5UkaH4GRCi5o6kI/WjmVmVwVw8iw="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20240102154912-e7106e64919e"
    hash = "sha256-2vwd2NSUOWQSuzGGOpdtz6FDGrLHER8vEAVC7wDlZ40="
  [mod."oras.land/oras-go"]
    version = "v1.2.4"
    hash = "sha256-rlfDvmk2kkV/qWRfed373v9Oof/4DNblDSx1tbd6QbE="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20221116044647-bc3834ca7abd"
    hash = "sha256-XDBMN2o450IHiAwEpBVsvo9e7tYZa+EXWrifUNTdNMU="
  [mod."sigs.k8s.io/kustomize/api"]
    version = "v0.16.0"
    hash = "sha256-GLh7SiGrKPRvxLj65x/4EkKbh6QVYn0I23SoVyvoxcs="
  [mod."sigs.k8s.io/kustomize/kyaml"]
    version = "v0.16.0"
    hash = "sha256-ou0pJ0oiRC/s6xETIa3fSMLDPKpWJP0MRpXOtf3lFPg="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.4.1"
    hash = "sha256-FcZHHZCKNNZW6/s1T1sKiS5Vj1TpHPmxVWr6YlL60xA="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.4.0"
    hash = "sha256-Hd/M0vIfIVobDd87eb58p1HyVOjYWNlGq2bRXfmtVno="
