---
apiVersion: v2
name: stackable-cockpit
version: "0.0.0-dev"
appVersion: "0.0.0-dev"
description: The Stackable Operator for Stackable Cockpit
home: https://github.com/stackabletech/stackable-cockpit
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
