---
name: pre-commit

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.80.1"
  HADOLINT_VERSION: "v1.17.6"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 #v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stackabletech/actions/run-pre-commit@9bd13255f286e4b7a654617268abe1b2f37c3e0a # v0.3.0
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          hadolint: ${{ env.HADOLINT_VERSION }}
