---
name: Pull Request Stackablectl

on:
  workflow_run:
    workflows: [Pull Request General]
    types: [completed]

env:
  RUST_VERSION: 1.70.0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  CARGO_PROFILE_DEV_DEBUG: "0"
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"
  RUST_LOG: "info"

jobs:
  check-files:
    name: Check for Changed Files
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      any_changed: ${{ steps.changes.outputs.any_changed }}
    steps:
      # This workflow is triggered when the 'Pull Request General' is completed.
      # This ensures that basic checks succeeded, indepent of the files changed.
      # To only run heavy and long-running jobs when required, we check if any
      # of the below listed files changes. Sadly, this requires an action, because
      # the 'workflow_run' trigger doesn't support the 'paths' field like the
      # 'pull:request' trigger does.
      - id: changes
        uses: tj-actions/changed-files@v39
        with:
          fail_on_initial_diff_error: true
          files: |
            .github/workflows/pr_stackablectl
            docs/modules/stackablectl
            rust/stackable-cockpit
            rust/stackablectl
            rust/helm-sys
            Cargo.lock
            go.sum
            extra
  build:
    name: Build stackablectl for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs:
      - check-files
    if: needs.check-files.outputs.any_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          key: build-stackablectl-${{ matrix.target }}
      - name: Build for non-Windows
        if: matrix.os != 'windows-latest'
        run: cargo build --target ${{ matrix.target }} -p stackablectl
